In [40]:
# 熵权法确定会员完成能力
# 将../data/有效会员信息数据.xlsx中的每位会员的预订任务限额作为指标1
# 将每位会员的预订任务开始时间与6:30的差值分钟数（3的倍数）作为指标2
# 若指标2不为0，则指标2更新为自己的倒数
# 若指标2为0，则指标2统一更新为常数0.5
# x_kj表示第k个会员的指标j的值

import pandas as pd
import numpy as np
import math

In [41]:
# 读取数据
data = pd.read_excel('../data/有效会员信息数据.xlsx')
data = data.dropna()
data = data.reset_index(drop=True)

print(data)

       会员编号          经度         纬度  预订任务限额  预订任务开始时间
0     B0001  113.679983  22.947097     114  06:30:00
1     B0002  113.966524  22.577792     163  06:30:00
2     B0003  113.347272  23.192458     139  06:30:00
3     B0004  113.318750  23.255965      98  06:30:00
4     B0006  112.797680  22.262784      72  06:30:00
...     ...         ...        ...     ...       ...
1869  B1873  113.277245  22.840505       1  08:00:00
1870  B1874  113.287606  23.069415       1  08:00:00
1871  B1875  113.301736  23.333446       1  08:00:00
1872  B1876  113.994101  22.693506       1  08:00:00
1873  B1877  113.239864  23.133238       1  08:00:00

[1874 rows x 5 columns]


In [46]:
# 计算指标1
x_1 = data['预订任务限额'].values
print(x_1)

# 计算指标2
x_21 = data['预订任务开始时间'].values
x_2 = []
for i in range(len(x_21)):
    time_parts = x_21[i].split(':')
    minutes = int(time_parts[0]) * 60 + int(time_parts[1]) + int(time_parts[2]) / 60
    x_2.append(minutes)
x_2 = np.array(x_2) - 390
print(x_2)

# 更新指标2
for i in range(len(x_2)):
    if x_2[i] != 0:
        x_2[i] = 1 / x_2[i]
    else:
        x_2[i] = 0.5
print(x_2)

# 用以上计算出的指标生成一份新的表格
data_new = pd.DataFrame()
data_new['会员编号'] = data['会员编号']
data_new['指标1'] = x_1
data_new['指标2'] = x_2
data_new.to_excel('../data/会员完成能力指标.xlsx', index=False)


[114 163 139 ...   1   1   1]
[ 0.  0.  0. ... 90. 90. 90.]
[0.5        0.5        0.5        ... 0.01111111 0.01111111 0.01111111]
